version: "3.8"

services:
  web:
    build: .
    ports:
      - "80:80"

  tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
    depends_on:
      - web
    environment:
      - BASE_URL=http://web:80